orbs:
  node: cicleci/node@2.0.2
  aws-cli: circleci/aws-cli@2.0.0
jobs:
  Test:
    machine:
      enabled: true
    steps :
      -run:
        name: Test
        command: ssh -i "circle.pem" ubuntu@ec2-13-235-68-44.ap-south-1.compute.amazonaws.com 'echo  "welcome"  ' ;
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      -Test:
        filters:
          branches:
            only: master
build_and_deploy-qa:
   jobs:
     -Test:
        filters:
          branches:
            only: master